#Read Me:
#    Developed By:
#                Name:Vaneeswaran N
#                www.vaneeswaran.com
#Descrption	: To pack the all required symbol files / libraries for the core that is generated.
#Arguments	: Core File Name 
#Output		: Tar ball with all symbol / libraries packed with the name corelibpack.tar

gdb -q --batch -c $1 | sed -ne "s/Core was generated by \`\(.*\)'\.$/\1/p"  > /tmp/pack_core_symbols.log
cut -d ' ' -f 1 < /tmp/pack_core_symbols.log > /tmp/pack_core_symbols.list
gdb -q -ex 'i sh' --batch -c $1  | sed -ne 's/^0x.*[[:space:]]\(\/.*\)/\1/p' >> /tmp/pack_core_symbols.list
tar -zcvf corelibpack.tar --files-from=/tmp/pack_core_symbols.list
